.rubocop.yml
yarr.gemspec

The current implementation has invalid ruby 2.4 syntax. For example:
```
def func
rescue
end
```
This becomes valid ruby after version 2.5. This PR changes the min ruby version to 2.5 and sets the `TargetRubyVersion` for rubocop.

Change the min ruby version to 2.5

---

lib/redis_record/relation.rb

This applies the changes from https://github.com/FB-PLP/traject/pull/1429/files. We are removing the redis-record implementation from traject and starting to maintain it here in this repo.

Apply traject/pull/1429

---

spec/spec_helper.rb
yarr.gemspec

This installs simplecov and codecov so we can attach a code coverage report on the PRs (we need to configure codecov.io for this repo).

Install simplecov and codecov

---

lib/redcord/serializer.rb

This is already merged in traject, patching the fix here for nilable time deserialization.
rspec spec/redis_record_spec.rb succeeds. I can follow up separately with better tests for this :)

Patch fix for nilable time deserialization

---

lib/redcord/attribute.rb
spec/attribute_spec.rb
spec/redis_record_spec.rb

This fixes some rubocop lint errors in `lib/redcord/attribute.rb`and separates its test cases into another file.

[refactor] Add attribute_spec

---

lib/redcord/base.rb
lib/redcord/server_scripts/create_hash_returning_id.erb.lua
spec/actions_spec.rb
spec/attribute_spec.rb

This sets default attributes such as id,created_at,updated_at to be indexed attributes so we can query those attributes using where and find_by
- Backward compatibility: existing records won't have index maintained, thus they're not visible to the where/find_by queries.
- Since the API is newly added, it could be fine to just treat the old records "does not exist" since the API is mainly for models created with a newer version of Redcord
- We can also run add_index migration for the existing records after this patch
Thoughts?

Make id,created_at,updated_at indexed attributes

---

lib/redcord/lua_script_reader.rb

This fixes an error when loading the redcord gem, as well as some rubocop lint errors.

[fix] Require erb in lua_script_reader

---

lib/redcord/migration/version.rb
spec/migration/version_spec.rb

This changes the mocking level in `migration/version_spec`, to cover more code path in rspec.

Increase test coverage in migration/version_spec

---

spec/migration/migrator_spec.rb

This mocks a rails application initialization process. It loads the config and runs `rake redis:migrate`in a spec environment.

Add migration/migrator_spec

---

lib/redcord/prepared_redis.rb
lib/redcord/railtie.rb

This fixes some errors that prevent the lib from working properly:
1. YAML.safe_load does not allow certain key names
2. Use the absolute script path instead

Fix loading errors

---

README.md
lib/redcord.rb
lib/redcord/actions.rb
lib/redcord/base.rb
lib/redcord/configurations.rb
lib/redcord/prepared_redis.rb
lib/redcord/railtie.rb
lib/redcord/relation.rb
lib/redcord/tracer.rb
spec/tracer_spec.rb

This allows users to add a tracer (for example, datadog's APM tracer) so the metrics/spans will be reported to the tracer.

Add tracer support

---

lib/redcord/logger.rb
lib/redcord/railtie.rb

Currently, the Redcord logger is always nil. We should set it after initializing the lib.

Set logger after init

---

lib/redcord/server_scripts/delete_hash.erb.lua
spec/relation_spec.rb

Fix updating the id index set when a redcord is destroyed
Spec to confirm cardinality of set is expected

Fix maintaining the id index set for the delete operation

---

lib/redcord/actions.rb
lib/redcord/attribute.rb
spec/actions_spec.rb

This allows us to find out the number of alive objects on a redis db.

[feature] Model.count

---

lib/redcord/serializer.rb
spec/serializer_spec.rb

When reviewing #72, I noticed currently we don't precisely send a float64 to redis; so currently they're not precisely stored on redis (suffer from precision loss).

Make float attr round-trippable

---

lib/redcord/serializer.rb
spec/actions_spec.rb
spec/serializer_spec.rb

https://apidock.com/ruby/Time/nsec
> The lowest digits of #to_f and #nsec are different because IEEE 754 double is not accurate enough to represent the exact number of nanoseconds since the Epoch.
> The more accurate value is returned by #nsec.
This converts time from a float to integer so it can become round-trippable.
**This is a breaking change!** The existing records are not compatible with the new version.

Make time attr round-trippable

---

README.md
lib/redcord/actions.rb
spec/actions_spec.rb

This implements Model#save, a non-raise version of save!. This API is identical to Rails activerecord.

[feature] Model#save

---

README.md
lib/redcord/actions.rb
spec/actions_spec.rb

This implements Model#update, a non-raise version of update!. This API is identical to Rails activerecord.

[feature] Model#update

---

README.md
lib/redcord/actions.rb
lib/redcord/attribute.rb
lib/redcord/relation.rb
lib/redcord/serializer.rb
spec/actions_spec.rb
spec/attribute_spec.rb
spec/custom_index_spec.rb
spec/migration/index_spec.rb
spec/relation_spec.rb
spec/serializer_spec.rb
spec/spec_helper.rb
spec/vacuum_spec.rb

Maintaining index sets for shard_by_attr is unnecessary. It's much more performant if we don't have to join it with other indices sets (especially when the other sets are ranged index sets -- we'd perform a loop join in the lua script).
This PR addresses the issue and enforces queries to contain at least 2 query conditions: the shard by attr condition, and another query condition on an indexed attribute (or more conditions).
For custom_index, the first attr (previously the shard_by_attr) is now removed -- the data in the zset for the first attr is the same for all records in the set anyway.

Skip maintaining index for shard_by_attr

---

lib/redcord/vacuum_helper.rb
spec/vacuum_spec.rb

Currently, the wild card matches not only the hast tags, but the nil index sets too when scanning.
- Added a test case which repros the issue
- ci

[bug] Fix vacuuming models with cluster mode on

---

lib/redcord/redis.rb
lib/redcord/relation.rb

Currently, the resource tag for create_hash_returning_id looks like `Redcord:ModelName` which is affecting the grouping on other resources. This fixes the issue by only tracing at actions/relation level

[bug] Fix tracer with resource tag

---

lib/redcord/redis.rb

This allows users to decide how many keys to fetch for each scan.
According to redis, the SCAN command
> The default COUNT value is 10
This is not ideal for our use case -- we gonna end up with too many round trips. I updated the default to 1000 (the same default batch size as activerecord)
- The changes are covered by spec
- ci

[feature] Custom scan_each_shard batch size

---

lib/redcord/connection_pool.rb
lib/redcord/redis_connection.rb
lib/redcord/relation.rb
redcord.gemspec
spec/connection_pool_spec.rb
spec/redis_connection_spec.rb

Add support for a connection pool Redis client if `pool` is specified in the configuration. This is intended to mimic how you can specify `pool` in the config/database.yml file, and overall the code is loosely based off of redis-memo's connection pool client: https://github.com/chanzuckerberg/redis-memo/blob/main/lib/redis_memo/connection_pool.rb
Currently trying this out in Along to see if it solves our issues with performance when running multi-threaded.

Add support for connection pooling in redcord

---

.github/workflows/build-publish.yaml
bin/publish-gem.sh
lib/redcord/relation.rb
spec/spec_helper.rb

Known issue where in Activesupport 7.0 you can't require subcomponents w/o first requiring ActiveSupport. This should fix it 
https://github.com/rails/rails/issues/43908
Also, Heavily borrowing from https://github.com/chanzuckerberg/SSRFs-Up/blob/main/.github/workflows/build-publish.yaml#L23-L42
Added secrets to repo

Require ActiveSupport and Publish redcord package whenever release is cut

---

.github/workflows/publish.yml
bin/publish-gem.sh

Trying to automatically publish gem but failing 
https://github.com/chanzuckerberg/redcord/actions/runs/1826850820
This should help 
So for background, redcord is an ORM we use in Traject.
It's published via github releases and then published to Rubygems.
Orgs using it will then pick up the update from rubygems
Usually this process happens manually.
But it's pretty easy to automate using CI. So this is adding a github action to publish a rubygem every time a release is cut in github.
I already had an attempt at this [here](https://github.com/chanzuckerberg/redcord/pull/92)
But my syntax wasn't exactly right

[publish gem] Build the gemspec, get rid of artifacts thing

---

redcord.gemspec

Gems are failing to build because they don't have a version in the gemspec that plays well.
Gotta bump the version in order to cut a new release I suppose ¯\_(ツ)_/¯
https://github.com/chanzuckerberg/redcord/runs/5208848654?check_suite_focus=true

Gotta bump the version in the gemspec

---

.github/workflows/ci.yml

Going to start truly supporting Ruby 3, and that starts from running in on CI; uses a hack to allow the CI to fail.
I plan on removing the 3.1 check as soon as possible!

ci: run on 3.1, ruby-head (allowing failures)

---

.github/workflows/ci.yml
.rubocop.yml
redcord.gemspec

Since 2.5, 2.6 have been EOL for a while - this PR removes them out of the officially supported range.

sets minimum ruby version to 2.7
